//! Vendor agent definitions with an explicit memory-server reference (P1.5).
//!
//! Emitted only when the reach record sets `explicit_ref_required`.
//! User-authored agent files are reported, never rewritten.

use std::path::{Path, PathBuf};

/// Claude `--agents` JSON for a `gaviero-worker` that names the server.
pub fn claude_agents_json(server_name: &str) -> String {
    serde_json::json!({
        "gaviero-worker": {
            "description": "Gaviero-owned worker that always sees the memory MCP server.",
            "prompt": "You are a Gaviero coding worker. Use the gaviero MCP tools when you need memory or graph context.",
            "mcpServers": [server_name]
        }
    })
    .to_string()
}

/// Claude `--agents` JSON when the workspace reach record requires an
/// explicit server list. Probe-supplied `agents_json` extra still wins.
pub fn claude_agents_json_if_required(root: &Path) -> Option<String> {
    let rec = super::reach::ReachStore::load(root).ok().flatten()?;
    let row = rec.providers.get("claude")?;
    row.explicit_ref_required
        .then(|| claude_agents_json("gaviero"))
}

/// Codex project agent TOML (inferred `mcp_servers` key; open check #3).
pub fn codex_agent_toml(server_name: &str) -> String {
    format!(
        "# Generated by Gaviero. Do not hand-edit if you want it regenerated.\n\
         name = \"gaviero-worker\"\n\
         description = \"Gaviero-owned worker that always sees the memory MCP server.\"\n\
         mcp_servers = [\"{server_name}\"]\n"
    )
}

/// Paths of user-authored agent files that do not mention `server_name`.
pub fn report_user_agent_definitions(root: &Path, server_name: &str) -> Vec<PathBuf> {
    let mut missing = Vec::new();
    scan_dir(
        &root.join(".claude").join("agents"),
        &["md", "json"],
        server_name,
        &mut missing,
    );
    scan_dir(
        &root.join(".codex").join("agents"),
        &["toml"],
        server_name,
        &mut missing,
    );
    missing.sort();
    missing
}

fn scan_dir(dir: &Path, exts: &[&str], server_name: &str, missing: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        let ext = path
            .extension()
            .and_then(|e| e.to_str())
            .unwrap_or("")
            .to_ascii_lowercase();
        if !exts.iter().any(|e| *e == ext) {
            continue;
        }
        let Ok(text) = std::fs::read_to_string(&path) else {
            missing.push(path);
            continue;
        };
        if !text.contains(server_name) {
            missing.push(path);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn claude_agents_json_names_mcp_servers() {
        let json = claude_agents_json("gaviero");
        let v: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert_eq!(v["gaviero-worker"]["mcpServers"][0], "gaviero");
    }

    #[test]
    fn codex_agent_toml_has_mcp_servers() {
        let toml = codex_agent_toml("gaviero");
        assert!(toml.contains("mcp_servers = [\"gaviero\"]"));
        assert!(toml.contains("name = \"gaviero-worker\""));
    }

    #[test]
    fn report_lists_files_lacking_the_server_name() {
        let dir = tempfile::tempdir().unwrap();
        let claude = dir.path().join(".claude").join("agents");
        std::fs::create_dir_all(&claude).unwrap();
        std::fs::write(claude.join("ok.md"), "mcpServers: [gaviero]\n").unwrap();
        std::fs::write(claude.join("missing.md"), "description: helper\n").unwrap();
        let report = report_user_agent_definitions(dir.path(), "gaviero");
        assert_eq!(report.len(), 1);
        assert!(report[0].ends_with("missing.md"));
    }
}
