//! Opt-in constitution → vendor skill file (`skills.emit`).
//!
//! Renders user-authored memories plus Decision / Convention / Invariant /
//! Preference (the chat-injection constitution filter) into
//! `gaviero-memory/SKILL.md` under `.claude/skills/` and `.codex/skills/`.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use crate::memory::ChatInjectionConfig;
use crate::workspace::{Workspace, settings};

pub const GENERATED_HEADER: &str =
    "<!-- generated by gaviero skills.emit; do not edit. Replace this file without this header to keep a hand-authored skill. -->\n";
pub const SKILL_NAME: &str = "gaviero-memory";
const DEFAULT_MAX_BYTES: usize = 8192;
const FRONTMATTER: &str = "---\nname: gaviero-memory\ndescription: Workspace decisions and conventions retained by Gaviero.\n---\n";

#[derive(Debug, Clone)]
pub struct EmitSettings {
    pub enabled: bool,
    pub max_bytes: usize,
    pub constitution_types: Vec<crate::memory::MemoryType>,
}

impl Default for EmitSettings {
    fn default() -> Self {
        Self { enabled: false, max_bytes: DEFAULT_MAX_BYTES, constitution_types: ChatInjectionConfig::default_constitution_types() }
    }
}

impl EmitSettings {
    pub fn from_workspace(workspace: &Workspace, root: Option<&Path>) -> Self {
        Self {
            enabled: workspace.resolve_setting(settings::SKILLS_EMIT_ENABLED, root).as_bool().unwrap_or(false),
            max_bytes: workspace.resolve_setting(settings::SKILLS_EMIT_MAX_BYTES, root).as_u64().and_then(|n| usize::try_from(n).ok()).unwrap_or(DEFAULT_MAX_BYTES),
            constitution_types: workspace.resolve_chat_injection_config(root).constitution_types,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ConstitutionItem {
    pub memory_type: String,
    pub content: String,
    pub user_authored: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EmitOutcome {
    Disabled,
    SkippedHandAuthored { path: PathBuf },
    Written { paths: Vec<PathBuf>, bytes: usize },
}

pub fn admit(item: &ConstitutionItem) -> bool {
    admitted(item, &ChatInjectionConfig::default_constitution_types())
}

fn admitted(item: &ConstitutionItem, types: &[crate::memory::MemoryType]) -> bool {
    item.user_authored || ChatInjectionConfig::types_from_names(&[item.memory_type.clone()]).iter().any(|ty| types.contains(ty))
}

pub fn render_body(items: &[ConstitutionItem], max_bytes: usize) -> String {
    render_with_types(items, max_bytes, &ChatInjectionConfig::default_constitution_types())
}

fn render_with_types(items: &[ConstitutionItem], max_bytes: usize, types: &[crate::memory::MemoryType]) -> String {
    let mut lines: Vec<String> = items
        .iter()
        .filter(|i| admitted(i, types))
        .map(|i| {
            format!(
                "- [{}] {}",
                i.memory_type.trim(),
                i.content.trim().replace('\n', " ")
            )
        })
        .collect();
    lines.sort();
    let mut body = String::from("# Gaviero memory\n\n");
    body.push_str("Workspace constitution the host injects on turn one. Pull more via MCP `memory_search` / `memory_get`.\n\n");
    for line in lines {
        body.push_str(&line);
        body.push('\n');
    }
    let mut out = format!("{FRONTMATTER}{GENERATED_HEADER}");
    if max_bytes < out.len() + 16 {
        return String::new();
    }
    let room = max_bytes - out.len();
    if body.len() <= room {
        out.push_str(&body);
    } else {
        let mut truncated = body;
        let mut end = room.saturating_sub(16).min(truncated.len());
        while !truncated.is_char_boundary(end) { end -= 1; }
        truncated.truncate(end);
        truncated.push_str("\n…truncated\n");
        out.push_str(&truncated);
    }
    out
}

fn skill_path(vendor_skills: &Path) -> PathBuf {
    vendor_skills.join(SKILL_NAME).join("SKILL.md")
}

fn is_hand_authored(path: &Path) -> bool {
    match std::fs::read_to_string(path) {
        Ok(s) => !(s.starts_with(GENERATED_HEADER) || s.strip_prefix(FRONTMATTER).is_some_and(|body| body.starts_with(GENERATED_HEADER))),
        Err(_) => true,
    }
}

fn write_one(path: &Path, body: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    use std::io::Write;
    let mut tmp = tempfile::NamedTempFile::new_in(path.parent().context("skill path has no parent")?)?;
    tmp.write_all(body.as_bytes())?;
    tmp.as_file().sync_all()?;
    tmp.persist(path).with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}

/// Write (or skip) both vendor skill files under `root`.
pub fn emit_memory_skill(
    root: &Path,
    items: &[ConstitutionItem],
    enabled: bool,
    max_bytes: usize,
) -> Result<EmitOutcome> {
    emit_with_settings(root, items, &EmitSettings { enabled, max_bytes, ..Default::default() })
}

fn emit_with_settings(root: &Path, items: &[ConstitutionItem], settings: &EmitSettings) -> Result<EmitOutcome> {
    let enabled = settings.enabled;
    let max_bytes = settings.max_bytes;
    if !enabled {
        return Ok(EmitOutcome::Disabled);
    }
    anyhow::ensure!(max_bytes >= FRONTMATTER.len() + GENERATED_HEADER.len() + 16, "skills.emit.maxBytes is too small for a valid generated skill");
    let body = render_with_types(items, max_bytes, &settings.constitution_types);
    let targets = [
        root.join(".claude").join("skills"),
        root.join(".codex").join("skills"),
    ];
    let mut written = Vec::new();
    let mut skipped = None;
    for dir in &targets {
        let path = skill_path(dir);
        if path.exists() && is_hand_authored(&path) {
            skipped = Some(path);
            continue;
        }
        write_one(&path, &body)?;
        written.push(path);
    }
    if written.is_empty() && let Some(path) = skipped {
        return Ok(EmitOutcome::SkippedHandAuthored { path });
    }
    Ok(EmitOutcome::Written {
        bytes: body.len(),
        paths: written,
    })
}

/// After consolidation: dump admitted constitution rows into vendor skill files.
pub async fn emit_after_consolidation(
    root: &Path,
    stores: &crate::memory::stores::MemoryStores,
    settings: &EmitSettings,
) -> Result<EmitOutcome> {
    if !settings.enabled {
        return Ok(EmitOutcome::Disabled);
    }
    let mut items = Vec::new();
    for (ty, content, user) in stores.workspace().list_for_skills_emit(512).await? {
        items.push(ConstitutionItem {
            memory_type: ty,
            content,
            user_authored: user,
        });
    }
    let root = root.to_path_buf();
    let settings = settings.clone();
    tokio::task::spawn_blocking(move || emit_with_settings(&root, &items, &settings)).await?
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn items() -> Vec<ConstitutionItem> {
        vec![
            ConstitutionItem {
                memory_type: "factual".into(),
                content: "user said hello".into(),
                user_authored: true,
            },
            ConstitutionItem {
                memory_type: "decision".into(),
                content: "use Write Gate".into(),
                user_authored: false,
            },
            ConstitutionItem {
                memory_type: "gotcha".into(),
                content: "skip me".into(),
                user_authored: false,
            },
        ]
    }

    #[test]
    fn constitution_filter_keeps_user_and_decision() {
        let body = render_body(&items(), 8192);
        assert!(body.contains("user said hello"));
        assert!(body.contains("use Write Gate"));
        assert!(!body.contains("skip me"));
        assert!(body.starts_with(FRONTMATTER));
    }

    #[test]
    fn cap_truncates() {
        let long = ConstitutionItem {
            memory_type: "decision".into(),
            content: "x".repeat(500),
            user_authored: false,
        };
        let body = render_body(&[long], 400);
        assert!(body.len() <= 400);
        assert!(body.contains("truncated"));
    }

    #[test]
    fn byte_stable_across_runs() {
        let a = render_body(&items(), 8192);
        let b = render_body(&items(), 8192);
        assert_eq!(a, b);
    }

    #[test]
    fn writes_both_vendor_dirs() {
        let dir = tempdir().unwrap();
        let out = emit_memory_skill(dir.path(), &items(), true, 8192).unwrap();
        match out {
            EmitOutcome::Written { paths, .. } => {
                assert_eq!(paths.len(), 2);
                for p in paths {
                    assert!(p.exists());
                    let s = std::fs::read_to_string(p).unwrap();
                    assert!(s.contains("generated by gaviero skills.emit"));
                }
            }
            other => panic!("{other:?}"),
        }
    }

    #[test]
    fn never_overwrites_hand_authored() {
        let dir = tempdir().unwrap();
        let path = dir
            .path()
            .join(".claude")
            .join("skills")
            .join("gaviero-memory")
            .join("SKILL.md");
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, "# mine\n").unwrap();
        let out = emit_memory_skill(dir.path(), &items(), true, 8192).unwrap();
        assert!(matches!(out, EmitOutcome::Written { ref paths, .. } if paths.len() == 1));
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "# mine\n");
    }

    #[test]
    fn disabled_is_noop() {
        let dir = tempdir().unwrap();
        let out = emit_memory_skill(dir.path(), &items(), false, 8192).unwrap();
        assert_eq!(out, EmitOutcome::Disabled);
        assert!(!dir.path().join(".claude").exists());
    }

    #[test]
    fn unicode_caps_preserve_valid_frontmatter() {
        let item = ConstitutionItem { memory_type: "decision".into(), content: "日本語🦀é".repeat(300), user_authored: false };
        for cap in 0..1000 {
            let body = render_body(std::slice::from_ref(&item), cap);
            assert!(body.len() <= cap);
            if !body.is_empty() {
                assert!(crate::skills::frontmatter::split_frontmatter(&body).0.is_some());
            }
        }
        let dir = tempdir().unwrap();
        assert!(emit_memory_skill(dir.path(), &[item], true, 0).is_err());
        assert!(!dir.path().join(".claude").exists());
    }

    #[test]
    fn marker_in_hand_authored_body_does_not_allow_overwrite() {
        let dir = tempdir().unwrap();
        let path = skill_path(&dir.path().join(".claude/skills"));
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        let authored = format!("# Manual instructions\nExample marker: {GENERATED_HEADER}");
        std::fs::write(&path, &authored).unwrap();
        emit_memory_skill(dir.path(), &items(), true, 8192).unwrap();
        assert_eq!(std::fs::read_to_string(path).unwrap(), authored);
        assert!(skill_path(&dir.path().join(".codex/skills")).exists());
    }

    #[test]
    fn configured_constitution_types_are_used() {
        let body = render_with_types(&items(), 8192, &[crate::memory::MemoryType::Gotcha]);
        assert!(body.contains("skip me"));
        assert!(body.contains("user said hello"));
        assert!(!body.contains("use Write Gate"));
    }
}
